############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: https://github.com/ruskicrew/ruskicrew.github.io/blox-plugin-netlify
  - path: https://github.com/ruskicrew/ruskicrew.github.io/modules/blox-tailwind
